comment:
  image:
    repository: dmitriydubikov/comment
    tag: logging
  service:
    externalPort: 9292

post:
  image:
    repository: dmitriydubikov/post
    tag: logging
    service:
      externalPort: 5000

ui:
  image:
    repository: dmitriydubikov/ui
    tag: logging
    service:
      externalPort: 9292
