global:
  slack_api_url: 'https://devops-team-otus.slack.com/messages/CHKBQ41HT'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitriy_dubikov'
