---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: comment-deployment
spec:
  replicas: 1
  # Указатель на то, какие поды нужно поддерживать в нужном количестве
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      name: comment
      labels:
        app: comment
    spec:
      containers:
      - image: dmitriydubikov/comment
        name: comment

